### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by cyberhardt** [Raimusoft/FoxTunes#123]
suggestion: add option to read and add files as they are organized (as-is). some of my files aren't tagged, or are not properly tagged (even after running musicbrainz picard), so they end up all scattered on the player under different albums and artists, or are just ignored. would be nice if I could simply see them as they are organized on my drive.

-

this is a pretty neat program, I have tried some music players, and they usually are either proprietary (foobar2000...), have many functions I don't need, lack WASAPI/ASIO (foobar again, and many others) or are buggy (musicbee...). My only complaint of sorts is that, as of now, it consumes quite a bit of RAM compared to most players I've tested. Also takes a while to start. It's not bad, but could be improved.

the fact you can navigate through artists and albums by the covers, the classic windows themes and full XP to 11 compatibility are great to see

**Comment by sophie-gilbert** [comment]
Try this build, you should be able to leave this setting blank which will preserve filesystem ordering:
![image](https://github.com/Raimusoft/FoxTunes/assets/13859177/16c6a502-1bf0-491d-a994-08749d257110)

https://github.com/Raimusoft/FoxTunes/actions/runs/5046202708

**Comment by cyberhardt** [comment]
ohhhhhhhhhhhhhhh nevermind I did it

**Comment by sophie-gilbert** [comment]
if that fixes your issue , create a fork and run the release pipeline. i'm not sure when i'll create a formal release on the main line.

**Comment by cyberhardt** [comment]
> if that fixes your issue , create a fork and run the release pipeline. i'm not sure when i'll create a formal release on the main line.

I was able to do that on 3.0.3 as well

**Comment by sophie-gilbert** [comment]
hmm i thought without https://github.com/Raimusoft/FoxTunes/commit/5de77b2291f96ae0af543d3effd3f2eace22b89a your playlists would be sorted incorrectly (not according to the file system i mean)

**Comment by sophie-gilbert** [comment]
RE memory usage , it's mostly related to the cover art in the library grid view thing. if memory is an issue i would try the "minimal" package and add only the plug-ins you need. alternatively try a simpler layout preset or avoid the "customisable" layout engine entirely

**Comment by cyberhardt** [comment]
I also figured that, in order for it to save the Folder Structure organization (so that it keeps it after a restart), it is necessary to place it on top of the other ones on Library, like this

![image](https://github.com/Raimusoft/FoxTunes/assets/107224222/b626314b-04b9-4baf-ad78-f3c3bb8bb95e)

> hmm i thought without [5de77b2](https://github.com/Raimusoft/FoxTunes/commit/5de77b2291f96ae0af543d3effd3f2eace22b89a) your playlists would be sorted incorrectly (not according to the file system i mean)

Such option exists on 3.0.3:

![image](https://github.com/Raimusoft/FoxTunes/assets/107224222/d9981f47-fbd2-4539-b9e2-3d0aca618dbb)

But it doesn't seem to have any impact on my files when File System is enabled

**Comment by sophie-gilbert** [comment]
yus , there was a bug where it would crash if you cleared the value for that setting , i changed it so if it's empty then sort by the file name
