### ISSUE TITLE
Add language support

### ISSUE THREAD

**Issue by DJCALIEND** [Raimusoft/FoxTunes#80]

**Comment by aidan-g** [comment]
It looks like this is quite complicated to do properly, due to the modular nature of the project we would need to create satalite assemblies for all plugins. Just adding two languages would result in an additional ~100 dlls! 

A simple resource loader was added in 4facf21947f0695e25b9e4c94c3a800af7bafd3a

**Comment by aidan-g** [comment]
Another translation example as added 96aaa3f3448a3f0d4ad81b4d191b8a1f40f12cbb.

**Comment by aidan-g** [comment]
The high value translation areas are `*Configuration.cs` files.

**Comment by Vistaus** [comment]
I support this and will provide the Dutch translation once you get this implemented :)

**Comment by aidan-g** [comment]
> 
> 
> I support this and will provide the Dutch translation once you get this implemented :)

An nl resourcing example was created in de4ff884cfd79116711fdc89bfad81a2f9b223d3.

**Comment by Vistaus** [comment]
Cool! How do I start translating that file?

**Comment by aidan-g** [comment]
> Cool! How do I start translating that file?

Basically copy the resource names from Strings.resx to Strings.nl.resx (in visual studio you can copy/paste like a spreadsheet) then update the resource values. 

I invited you to the teams channel, I can provide more details there.

**Comment by DJCALIEND** [comment]
FR-FR translation is on the way.

**Comment by aidan-g** [comment]
Closing as this feature is managing itself.
