### ISSUE TITLE
Resampler only works on DirectSound, Please Implement it in ASIO & WASAPI !

### ISSUE THREAD

**Issue by xerxeshowie** [Raimusoft/FoxTunes#97]
Resampler only works on DirectSound, Please Implement it in ASIO & WASAPI !

**Comment by aidan-g** [comment]
It seems to work for me, please view the instructions at https://github.com/aidan-g/FoxTunes/wiki/Plugin-Instructions#resampler-sox

If this is still an issue please post;

1) Log.txt
2) Settings.xml
3) The audio file that presents this issue.
4) Your expectations.

**Comment by aidan-g** [comment]
Ensure your desired sample rate and the "enforce rate" options are set, works for me.
